//@ts-ignore
import { Bytes, Event } from "@hyperoracle/zkgraph-lib";
import { Pay } from "./utils/parser";

/**
 * The idea of analyzing the Liquidator Pay event
 * is to find the second Pay event in each Transaction.
 * The value of this Pay event is profit.
 *
 * @param {Event[]} events - The list of Event objects to handle.
 * @return {Bytes} The generated Bytes object.
 */
export function handleEvents(events: Event[]): Bytes {
  let resultBytes = Bytes.empty();

  for (let i = 0; i <= events.length - 1; i++) {
    if (i % 2) {
      const enter = Pay.fromEvent(events[i]);
      resultBytes.concat(enter.toBytes());
    }
  }

  return resultBytes;
}
